# Generated by Django 2.2.9 on 2020-02-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immortal_2020', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Country',
        ),
    ]
