# Generated by Django 2.2.9 on 2020-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immortal_2020', '0002_remove_project_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
